apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-mygraph-neo4j-core-0
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi