apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-mygraph-neo4j-core-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  nfs:
    server: zhome.geos.tamu.edu
    path: "/pvstorage"